[project]
name = "exercicio-ebac-django"
version = "0.1.0"
description = ""
authors = [
    {name = "juliocouteau", email = "juliosantss5334@hotmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "django>=4.2.7",
    "djangorestframework>=3.14.0",
    "gunicorn",
    "dj-database-url",
    "whitenoise",
    "psycopg2-binary"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"