name: Django CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Instalar Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Gerar requirements.txt e Build Docker
      run: |
        poetry export -f requirements.txt --output requirements.txt
        docker build -t bookstore-test .